server:
  port: 8081

spring:
  application:
    admin:
      enabled: true
    name: external-service
  jackson:
    serialization:
      write_dates_as_timestamps: false
    mapper:
      default_view_inclusion: true
    default-property-inclusion: 'non_null'
  mail:
    host: smtp.gmail.com
    port: 587
    username: exrates.2019@gmail.com
    password: 123qwe123QWE
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
#  rabbitmq:
#    username: developer
#    password: eehei4AeJein
#    host: rabbitmq-dev.service
#    port: 5672
#    trades-topic: EXTERNAL_DATA_QUEUE_DEV
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
    trades-topic: EXTERNAL_DATA_QUEUE

#datasource:
#  driver-class-name: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/birzha?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#  username: root
#  password: root
datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://exdbdev.cedlveyttji9.us-east-2.rds.amazonaws.com:3306/dbdev2?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  username: exdevdb
  password: KQmK82dd

application:
  base-url: http://localhost:8081
  security:
    authorization-secret: external-service-2019
  email:
#    address: oleg.kostiukevych@upholding.biz
    address: exrates.2019@gmail.com
    name: Exrates
    title-prefix:
  authorize:
    2fa-required: true
  allowed-resolutions: 5, 5M, 15, 15M, 30, 30M, 60, 1H, 360, 6H, 1440, 1D

stream.result.size: 100

#api:
#  chart:
#    url: http://chart-service-dev.service:4104/data
#    coinmarketcap-url: http://chart-service-dev.service:4104/coinmarketcap
api:
  chart:
    url: http://localhost:8060/data
    coinmarketcap-url: http://localhost:8060/coinmarketcap

# 1. create new email for this service or use old one
# 2. fix and add new information to email .html and .ftl
# 3. add new database acccount with writes:
# CURRENCY_PAIR, 2FA_GOOGLE_AUTHENTICATOR - read
# USER - write