server:
  port: 8081

spring:
  application:
    admin:
      enabled: true
    name: external-service
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/external?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: root
#    password: root
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://exdbdev.cedlveyttji9.us-east-2.rds.amazonaws.com:3306/dbdev2?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: exdevdb
    password: KQmK82dd
  jackson:
    serialization:
      write_dates_as_timestamps: false
    mapper:
      default_view_inclusion: true
    default-property-inclusion: 'non_null'
  mail:
    host: smtp.gmail.com
    port: 587
    username: exrates.2019@gmail.com
    password: 123qwe123QWE
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
#  rabbitmq:
#    username: developer
#    password: eehei4AeJein
#    host: rabbitmq-dev.service
#    port: 5672
#    trades-topic: CHART_DATA_QUEUE_DEV
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
    trades-topic: EXTERNAL_SERVICE_TRADES_QUEUE
    orders-topic: EXTERNAL_SERVICE_ORDERS_QUEUE

application:
  base-url: http://localhost:8081
  security:
    authorization-secret: external-service-2019
  email:
    address: oleg.kostiukevych@upholding.biz
    name: Exrates
    title-prefix:
  authorize:
    2fa-required: true
  allowed-resolutions: >
    5 MINUTE;
    15 MINUTE;
    30 MINUTE;
    1 HOUR;
    6 HOUR;
    1 DAY;

api:
  exrates:
#    url: http://172.31.14.167:8080/openapi/v1
    url: http://localhost:8080/openapi/v1